return {
   "zaldih/themery.nvim",
   enabled = false,
   lazy = false,
   config = function()
      require("themery").setup {
         themes = {
            "catppuccin-frappe",
            "catppuccin-macchiato",
            "catppuccin-mocha",
            "tokyonight-storm",
            "tokyonight-moon",
            "tokyonight-night",
            "blue",
            "darkblue",
            "default",
            "desert",
            "elflord",
            "evening",
            "habamax",
            "industry",
            "koehler",
            "lunaperche",
            "minicyan",
            "minischeme",
            "murphy",
            "pablo",
            "ron",
            "slate",
            "sorbet",
            "torte",
            "unokai",
            "vim",
            "wildcharm",
            "zaibatsu",
            "catppuccin-latte",
            "tokyonight-day",
            "delek",
            "morning",
            "peachpuff",
            "quiet",
            "randomhue",
            "retrobox",
            "shine",
            "zellner",
         },
         livePreview = true,
      }
   end,
}
